# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.14"
  amd64: "ghcr.io/home-assistant/amd64-base:3.14"
  armhf: "ghcr.io/home-assistant/armhf-base:3.14"
  armv7: "ghcr.io/home-assistant/armv7-base:3.14"
  i386: "ghcr.io/home-assistant/i386-base:3.14"
labels:
  org.opencontainers.image.title: "Xolta battery authentication service"
  org.opencontainers.image.description: "Service for getting access tokens for the Xolta battery app API using selenium."
  org.opencontainers.image.source: "https://github.com/AThomsen/home-assistant_xolta_battery_authentication-addon"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
