name: "Xolta Battery authentication"
description: "Service for getting access tokens for the Xolta battery app API"
version: "1.1.0"
slug: "xolta_batt_auth_addon"
init: false
arch:
  - aarch64
  - amd64
  - armv7
startup: services
